### ISSUE TITLE
Netty runtime error

### ISSUE THREAD

**Issue by leolux** [vert-x3/vertx-4-migration-guide#77]
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/handler/logging/ByteBufFormat
	at io.vertx.core.net.NetworkOptions.<clinit>(NetworkOptions.java:60)
	at io.vertx.core.VertxOptions.<init>(VertxOptions.java:130)
	at io.vertx.core.Vertx.vertx(Vertx.java:77)

How to fix that?

**Comment by tsegismont** [comment]
Sound like the `netty-handler` jar is missing at runtime. This is not a migration issue, I think. Probably a build issue.
